# Generated by Django 5.0.6 on 2026-04-13 17:42

from django.db import migrations


RECONCILE_ANALYTICS_SCHEMA_SQL = """
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_class
        WHERE relkind = 'i' AND relname = 'analytics_c_link_id_clicked_at_idx'
    ) AND NOT EXISTS (
        SELECT 1
        FROM pg_class
        WHERE relkind = 'i' AND relname = 'analytics_c_link_id_ff89ee_idx'
    ) THEN
        ALTER INDEX analytics_c_link_id_clicked_at_idx RENAME TO analytics_c_link_id_ff89ee_idx;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_class
        WHERE relkind = 'i' AND relname = 'analytics_c_clicked_at_idx'
    ) AND NOT EXISTS (
        SELECT 1
        FROM pg_class
        WHERE relkind = 'i' AND relname = 'analytics_c_clicked_ca1c42_idx'
    ) THEN
        ALTER INDEX analytics_c_clicked_at_idx RENAME TO analytics_c_clicked_ca1c42_idx;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS analytics_deviceinfo (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_address inet NOT NULL,
    device_model varchar(255) NOT NULL DEFAULT 'Unknown',
    device_type varchar(50) NOT NULL DEFAULT 'unknown',
    user_agent varchar(500) NOT NULL DEFAULT '',
    country varchar(100) NOT NULL DEFAULT 'Unknown',
    country_code varchar(2) NOT NULL DEFAULT '',
    city varchar(100) NOT NULL DEFAULT 'Unknown',
    region varchar(100) NOT NULL DEFAULT '',
    latitude double precision NULL,
    longitude double precision NULL,
    timezone varchar(50) NOT NULL DEFAULT '',
    isp varchar(255) NOT NULL DEFAULT '',
    first_access timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_access timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    access_count integer NOT NULL DEFAULT 1,
    link_id bigint NOT NULL REFERENCES links_link (id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT analytics_deviceinfo_access_count_check CHECK (access_count >= 0),
    CONSTRAINT analytics_deviceinfo_link_id_ip_address_unique UNIQUE (link_id, ip_address)
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_class
        WHERE relkind = 'i' AND relname = 'analytics_d_link_id_idx'
    ) AND NOT EXISTS (
        SELECT 1
        FROM pg_class
        WHERE relkind = 'i' AND relname = 'analytics_d_link_id_41e5f8_idx'
    ) THEN
        ALTER INDEX analytics_d_link_id_idx RENAME TO analytics_d_link_id_41e5f8_idx;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_class
        WHERE relkind = 'i' AND relname = 'analytics_d_country_code_idx'
    ) AND NOT EXISTS (
        SELECT 1
        FROM pg_class
        WHERE relkind = 'i' AND relname = 'analytics_d_country_c86a87_idx'
    ) THEN
        ALTER INDEX analytics_d_country_code_idx RENAME TO analytics_d_country_c86a87_idx;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS analytics_d_link_id_41e5f8_idx
    ON analytics_deviceinfo (link_id, last_access DESC);

CREATE INDEX IF NOT EXISTS analytics_d_country_c86a87_idx
    ON analytics_deviceinfo (country_code);
"""


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=RECONCILE_ANALYTICS_SCHEMA_SQL,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='clickevent',
                    new_name='analytics_c_link_id_ff89ee_idx',
                    old_name='analytics_c_link_id_clicked_at_idx',
                ),
                migrations.RenameIndex(
                    model_name='clickevent',
                    new_name='analytics_c_clicked_ca1c42_idx',
                    old_name='analytics_c_clicked_at_idx',
                ),
                migrations.RenameIndex(
                    model_name='deviceinfo',
                    new_name='analytics_d_link_id_41e5f8_idx',
                    old_name='analytics_d_link_id_idx',
                ),
                migrations.RenameIndex(
                    model_name='deviceinfo',
                    new_name='analytics_d_country_c86a87_idx',
                    old_name='analytics_d_country_code_idx',
                ),
            ],
        ),
    ]
