# Generated by Django 5.0.6 on 2026-04-13 17:42

from django.db import migrations


RENAME_LINK_INDEXES_SQL = """
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_class
        WHERE relkind = 'i' AND relname = 'links_l_short_code_idx'
    ) AND NOT EXISTS (
        SELECT 1
        FROM pg_class
        WHERE relkind = 'i' AND relname = 'links_link_short_c_886f39_idx'
    ) THEN
        ALTER INDEX links_l_short_code_idx RENAME TO links_link_short_c_886f39_idx;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_class
        WHERE relkind = 'i' AND relname = 'links_l_owner_created_at_idx'
    ) AND NOT EXISTS (
        SELECT 1
        FROM pg_class
        WHERE relkind = 'i' AND relname = 'links_link_owner_i_d4ad2a_idx'
    ) THEN
        ALTER INDEX links_l_owner_created_at_idx RENAME TO links_link_owner_i_d4ad2a_idx;
    END IF;
END $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=RENAME_LINK_INDEXES_SQL,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='link',
                    new_name='links_link_short_c_886f39_idx',
                    old_name='links_l_short_code_idx',
                ),
                migrations.RenameIndex(
                    model_name='link',
                    new_name='links_link_owner_i_d4ad2a_idx',
                    old_name='links_l_owner_created_at_idx',
                ),
            ],
        ),
    ]
